
["Fire Extinguisher"]
	#The radius around the target block to stop fire.
	#Range: 0 ~ 8
	fireExtinguisherRadius = 2

["Fire Axt"]
	#The radius around the target block to stop fire.
	#Range: 0 ~ 8
	fireAxtRadius = 1

["Fire Sprinkler"]
	#The Manhattan distance around the target block to spread water in X direction.
	#Range: 0 ~ 8
	fireSprinklerRadiusX = 2
	#The Manhattan distance around the target block to spread water in Y direction.
	#Range: 0 ~ 8
	fireSprinklerRadiusY = 3
	#The Manhattan distance around the target block to spread water in Z direction.
	#Range: 0 ~ 8
	fireSprinklerRadiusZ = 2

["Smoke Detector"]
	#The Manhattan distance around the target block to detect fire in X direction.
	#Range: 0 ~ 8
	smokeDetectorRadiusX = 3
	#The Manhattan distance around the target block to detect fire in Y direction.
	#Range: 0 ~ 8
	smokeDetectorRadiusY = 5
	#The Manhattan distance around the target block to detect fire in Z direction.
	#Range: 0 ~ 8
	smokeDetectorRadiusZ = 3

["Fire Protection (heavy)"]
	#Enable/Disable fire protection affects from fire armor.
	fireProtectionEnabled = true
	#Defines the amount of ticks after the fire protection get's renewed.
	#Range: 20 ~ 6000
	fireProtectionRenew = 80
	#Defines the amount of ticks how long the fire protection is enabled.
	#Range: 10 ~ 6000
	fireProtectionDuration = 25

	["Fire Protection (heavy)"."Fire Boots"]
		#Enable/Disable slow down effect of wearing the fire boots.
		fireBootsSlowDownEnabled = true

	["Fire Protection (heavy)"."Fire Chestplate"]
		#Enable/Disable slow down effect of wearing the fire chestplate.
		fireChestplateSlowDownEnabled = true

	["Fire Protection (heavy)"."Fire Leggings"]
		#Enable/Disable slow down effect of wearing the fire leggings.
		fireLeggingsSlowDownEnabled = true

["Fire Protection (light)"]
	#Enable/Disable fire protection light affects from fire armor.
	fireProtectionLightEnabled = true
	#Defines the amount of ticks after the fire protection light get's renewed.
	#Range: 20 ~ 6000
	fireProtectionLightRenew = 180
	#Defines the amount of ticks how long the fire protection light is enabled.
	#Range: 10 ~ 6000
	fireProtectionLightDuration = 40

